name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - openjdk=11.0.8
  - pip:
      - pandas
      - numpy==1.23.5
      - scikit-learn==1.3.2
      - azureml-core
      - azureml-dataset-runtime[fuse]
      - pyspark==3.2.1
      - azureml-featurestore>=1.1.0
